/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImagesResponse struct {

	Created int32 `json:"created"`

	Data []ImagesResponseDataInner `json:"data"`
}
