/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FineTuneEvent struct {

	Object string `json:"object"`

	CreatedAt int32 `json:"created_at"`

	Level string `json:"level"`

	Message string `json:"message"`
}
