/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateChatCompletionRequestStop - Up to 4 sequences where the API will stop generating further tokens. 
type CreateChatCompletionRequestStop struct {
}
