/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateSearchRequest struct {

	// Query to search against the documents.
	Query string `json:"query"`

	// Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both. 
	Documents *[]string `json:"documents,omitempty"`

	// The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both. 
	File *string `json:"file,omitempty"`

	// The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set. 
	MaxRerank *int32 `json:"max_rerank,omitempty"`

	// A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set. 
	ReturnMetadata *bool `json:"return_metadata,omitempty"`

	// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). 
	User string `json:"user,omitempty"`
}
