/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEmbeddingResponse struct {

	Object string `json:"object"`

	Model string `json:"model"`

	Data []CreateEmbeddingResponseDataInner `json:"data"`

	Usage CreateEmbeddingResponseUsage `json:"usage"`
}
