/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateAnswerResponse struct {

	Object string `json:"object,omitempty"`

	Model string `json:"model,omitempty"`

	SearchModel string `json:"search_model,omitempty"`

	Completion string `json:"completion,omitempty"`

	Answers []string `json:"answers,omitempty"`

	SelectedDocuments []CreateAnswerResponseSelectedDocumentsInner `json:"selected_documents,omitempty"`
}
