/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateClassificationResponse struct {

	Object string `json:"object,omitempty"`

	Model string `json:"model,omitempty"`

	SearchModel string `json:"search_model,omitempty"`

	Completion string `json:"completion,omitempty"`

	Label string `json:"label,omitempty"`

	SelectedExamples []CreateClassificationResponseSelectedExamplesInner `json:"selected_examples,omitempty"`
}
