/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateModerationResponse struct {

	Id string `json:"id"`

	Model string `json:"model"`

	Results []CreateModerationResponseResultsInner `json:"results"`
}
