/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImagesResponseDataInner struct {

	Url string `json:"url,omitempty"`

	B64Json string `json:"b64_json,omitempty"`
}
