/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChatCompletionRequestMessage struct {

	// The role of the author of this message.
	Role string `json:"role"`

	// The contents of the message
	Content string `json:"content"`

	// The name of the user in a multi-user chat
	Name string `json:"name,omitempty"`
}
