/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEmbeddingResponseUsage struct {

	PromptTokens int32 `json:"prompt_tokens"`

	TotalTokens int32 `json:"total_tokens"`
}
